// export { albumList, genresList };

export const albumList = [
  {
    id: 1,
    title: "Acabou o Chorare",
    genre: "MPB",
    price: 66.0,
    img: "./src/assets/img/1.jpg",
    band: "Novos Baianos",
    year: 1972,
  },
  {
    id: 2,
    title: "Clube da Esquina",
    genre: "MPB",
    price: 72.0,
    img: "./src/assets/img/2.jpg",
    band: "Milton Nascimento, Lô Borges, e outros",
    year: 1972,
  },
  {
    id: 3,
    title: "Elis & Tom",
    genre: "MPB",
    price: 68.0,
    img: "./src/assets/img/3.jpg",
    band: "Elis Regina e Tom Jobim",
    year: 1974,
  },
  {
    id: 4,
    title: "Thriller",
    genre: "Pop",
    price: 75.0,
    img: "./src/assets/img/4.jpg",
    band: "Michael Jackson",
    year: 1982,
  },
  {
    id: 5,
    title: "Bad",
    genre: "Pop",
    price: 40.0,
    img: "./src/assets/img/4.jpg",
    band: "Michael Jackson",
    year: 1987,
  },
  {
    id: 6,
    title: "Kind of Blue",
    genre: "Jazz",
    price: 80.0,
    img: "./src/assets/img/3.jpg",
    band: "Miles Davis",
    year: 1959,
  },
  {
    id: 7,
    title: "The Dark Side of the Moon",
    genre: "Rock",
    price: 85.0,
    img: "./src/assets/img/2.jpg",
    band: "Pink Floyd",
    year: 1973,
  },
  {
    id: 8,
    title: "Abbey Road",
    genre: "Rock",
    price: 88.0,
    img: "./src/assets/img/1.jpg",
    band: "The Beatles",
    year: 1969,
  },
  {
    id: 9,
    title: "Legend",
    genre: "Reggae",
    price: 31.0,
    img: "./src/assets/img/1.jpg",
    band: "Bob Marley & The Wailers",
    year: 1984,
  },
  {
    id: 10,
    title: "Illmatic",
    genre: "Rap",
    price: 79.0,
    img: "./src/assets/img/2.jpg",
    band: "Nas",
    year: 1994,
  },
  {
    id: 11,
    title: "To Pimp a Butterfly",
    genre: "Rap",
    price: 82.0,
    img: "./src/assets/img/3.jpg",
    band: "Kendrick Lamar",
    year: 2015,
  },
  {
    id: 12,
    title: "The Miseducation of Lauryn Hill",
    genre: "R&B",
    price: 76.0,
    img: "./src/assets/img/4.jpg",
    band: "Lauryn Hill",
    year: 1998,
  },
  {
    id: 13,
    title: "Enter the Wu-Tang (36 Chambers)",
    genre: "Hip-Hop",
    price: 74.0,
    img: "./src/assets/img/3.jpg",
    band: "Wu-Tang Clan",
    year: 1993,
  },
  {
    id: 14,
    title: "Doo-Wops & Hooligans",
    genre: "Pop",
    price: 67.0,
    img: "./src/assets/img/2.jpg",
    band: "Bruno Mars",
    year: 2010,
  },
  {
    id: 15,
    title: "Canta Canta, Minha Gente",
    genre: "Samba",
    price: 63.0,
    img: "./src/assets/img/1.jpg",
    band: "Martinho da Vila",
    year: 1974,
  },
];

export const genresList = [
  "Todos",
  "Pop",
  "MPB",
  "Samba",
  "Rap",
  "Hip-Hop",
  "Jazz",
  "Rock",
  "Reggae",
];

